### ISSUE TITLE
unable to load module after pip install

### ISSUE THREAD

**Issue by spetti** [hazimehh/hierScale#1]
I haven't been able to load hierScale after installing with pip. When I unzip the wheel file, I don't see any scripts in the scripts directory. Thanks!

**Comment by XiaoZhangryy** [comment]
I have the same problem as spetti. I can't import hierScale after installing using pip. Thanks!

**Comment by hazimehh** [comment]
Sorry for the delay. This might have been due to a compatibility issue with numba. We just released a new version that fixes this issue. Can you please try reinstalling the package using: pip install --no-cache-dir --upgrade hierScale
